### ISSUE TITLE
Bug: Can't paste into empty editor 

### ISSUE THREAD

**Issue by fameoflight** [facebook/lexical#2308]
Lexical version: 0.29 

## Steps To Reproduce

1. Load Editor with state '{}' 
2. Paste any content 

## The current behavior
```
index.tsx:91 Uncaught Error: replace: cannot be called on root nodes
    at RootNode.replace (Lexical.dev.js:7240:1)
    at RangeSelection.insertNodes (Lexical.dev.js:4729:1)
    at $basicInsertStrategy (LexicalClipboard.dev.js:285:1)
    at Object.$insertDataTransferForRichText (LexicalClipboard.dev.js:246:1)
    at LexicalRichText.dev.js:250:1
    at processNestedUpdates (Lexical.dev.js:3283:1)
    at beginUpdate (Lexical.dev.js:3335:1)
    at updateEditor (Lexical.dev.js:3423:1)
    at LexicalEditor.update (Lexical.dev.js:8661:1)
    at triggerCommandListeners (Lexical.dev.js:3196:1)
```
## The expected behavior
The paste should work as expected

**Comment by fameoflight** [comment]
How should it work with Placeholder then? If I have some text than Placeholder wouldn't show

**Comment by fameoflight** [comment]
Cool, thank you so much. I still think this is weird behavior, but leave it to your better judgement

**Comment by mattslight** [comment]
this is confusing me. I am not clear on the solution here. When I initiate the editor I should also add a ParagraphNode to root before I can insert text?

**Comment by trueadm** [comment]
You need to insert a paragraph node, then select the paragraph node, then insert the nodes.

```js
const paragraph = $createParagraphNode();
$getRoot().append(paragraph);
paragraph.select();
$insertNodes(nodes);
```

**Comment by mattslight** [comment]
Doesn't seem to resolve the issue. I'm guessing it's something to do with the nodes that $generateNodesFromDOM is generating. Looking at the previous structures I shared, should the TextNodes be associated by a ParagraphNode?

<img width="561" alt="Screenshot 2023-01-14 at 6 45 23 PM" src="https://user-images.githubusercontent.com/1073639/212477725-9c2d3410-5cb6-4e34-9307-f9e01eed0001.png">

**Comment by mattslight** [comment]
This workaround /hack seems to work

```javascript
// Generate LexicalNodes from DOM instance
const nodes = $generateNodesFromDOM(editor, dom);

// Select the root
$getRoot().select();
$getSelection();
console.log(editor);
nodes.forEach((node) => console.log(node));
if (nodes[0]?.__type == "list") {
  const paragraph = $createParagraphNode();
  $insertNodes([paragraph, ...nodes]);
} else {
  $insertNodes(nodes, true);
}
```

**Comment by mattslight** [comment]
Will have a look at it again tomorrow with fresh eyes, thanks again for your help @trueadm
