### ISSUE TITLE
Bug: $generateNodesFromDOM creates empty list items from whitespace between actual list items

### ISSUE THREAD

**Issue by knpwrs** [facebook/lexical#2807]
Lexical version: 0.3.8

## Steps To Reproduce

1. Use the following code to initialize Lexical:

```js
  editorState: (editor) => {
    const parser = new DOMParser();
    const dom = parser.parseFromString(
      "<ul><li>foo</li> <li>bar</li> <li>banana</li></ul>",
      "text/html"
    );
    const nodes = $generateNodesFromDOM(editor, dom);
    const rootNode = $getRoot();
    rootNode.append(...nodes);
  }
```

2. Observe that the empty spaces between the `<li>` elements get converted to empty list item nodes:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/174864/183986766-fc4c42f3-d208-46fd-8dca-6c0e6a167d60.png">

3. If you delete the extra spaces, the list will have the correct number of list items.

Link to code example: https://codesandbox.io/s/lexical-list-parsing-bug-ktssb4?file=%2Fsrc%2FEditor.js%3A1849-2160

## The current behavior

Empty list items are created from whitespace text nodes between list item nodes.

## The expected behavior

The empty whitespace between list items should be ignored.

**Comment by knpwrs** [comment]
This appears to be at least somewhat intentional: https://github.com/facebook/lexical/blob/b7887a02780e40640cf0e7582212f9c29730c14d/packages/lexical-list/src/LexicalListNode.ts#L251

https://github.com/facebook/lexical/pull/2509

**Comment by marwan38** [comment]
I came here to post this issue. If it is intentional then this PR will get closed anyways, but, worth sharing my use-case. Unlike OP, I am getting an error thrown. 

```js
  editorState: (editor) => {
    const parser = new DOMParser();
    const dom = parser.parseFromString(
      "<p>foo</p> <p>bar</p>", // NOTE THE SPACE BETWEEN THE P TAGS
      "text/html"
    );
    const nodes = $generateNodesFromDOM(editor, dom);
    const rootNode = $getRoot();
    rootNode.append(...nodes); // ERROR
  }
```

Error + stack trace
```js
Error: rootNode.append: Only element or decorator nodes can be appended to the root node
    at RootNode.append (**/node_modules/lexical/Lexical.dev.js:7667:17)
```

That empty space is creating empty nodes in between the paragraph ones which is why they then can't be inserted into the root node.

**Comment by SzDani3l** [comment]
> I came here to post this issue. If it is intentional then this PR will get closed anyways, but, worth sharing my use-case. Unlike OP, I am getting an error thrown.
> 
> ```js
>   editorState: (editor) => {
>     const parser = new DOMParser();
>     const dom = parser.parseFromString(
>       "<p>foo</p> <p>bar</p>", // NOTE THE SPACE BETWEEN THE P TAGS
>       "text/html"
>     );
>     const nodes = $generateNodesFromDOM(editor, dom);
>     const rootNode = $getRoot();
>     rootNode.append(...nodes); // ERROR
>   }
> ```
> 
> Error + stack trace
> 
> ```js
> Error: rootNode.append: Only element or decorator nodes can be appended to the root node
>     at RootNode.append (**/node_modules/lexical/Lexical.dev.js:7667:17)
> ```
> 
> That empty space is creating empty nodes in between the paragraph ones which is why they then can't be inserted into the root node.

I had the same issue, for now I fixed it by skipping the invalid nodes:

```
import { $getRoot, $isDecoratorNode, $isElementNode } from 'lexical'

[...]

const nodes = $generateNodesFromDOM(editor, dom)
const root = $getRoot()
root.getFirstDescendant()?.remove()
	nodes.forEach((node, i) => {
		if ($isElementNode(node) || $isDecoratorNode(node)) {
			root.append(node)
		}
	})
}
```

**Comment by kevinansfield** [comment]
I believe this can be closed now, I have code that uses `$generateNodesFromDOM` and added a [test for this case](https://github.com/TryGhost/Koenig/pull/1404/files#diff-de14adf9621833ea5d736de6fa012ca7652047a3f44a2c9bfbf73343bcd0766cR89-R101) which shows it no longer creates blank list items, at least when using 0.13.1.
