### ISSUE TITLE
Bug: getDOMSelection triggers `window is not defined` reference error in Next.js

### ISSUE THREAD

**Issue by donpark** [facebook/lexical#3095]
During full build and initial loading and rendering of Next.js app page using Lexical editor, [following line](https://github.com/facebook/lexical/blob/b3d927f783d7403515c6e5fc904e150a9ac8b2ff/packages/shared/src/getDOMSelection.ts#L9) in `shared/getDOMSelection.ts`

```typescript
const getSelection = (): Selection | null => window.getSelection();
```

triggers following error:

```
ReferenceError: window is not defined
    at getSelection (/Users/don/dev/haunted/node_modules/.pnpm/lexical@0.5.0/node_modules/lexical/Lexical.dev.js:68:35)
    at internalCreateSelection (/Users/don/dev/haunted/node_modules/.pnpm/lexical@0.5.0/node_modules/lexical/Lexical.dev.js:5028:24)
    at beginUpdate (/Users/don/dev/haunted/node_modules/.pnpm/lexical@0.5.0/node_modules/lexical/Lexical.dev.js:6021:39)
    at updateEditor (/Users/don/dev/haunted/node_modules/.pnpm/lexical@0.5.0/node_modules/lexical/Lexical.dev.js:6116:5)
    at LexicalEditor.update (/Users/don/dev/haunted/node_modules/.pnpm/lexical@0.5.0/node_modules/lexical/Lexical.dev.js:9115:5)
    at initializeEditor (/Users/don/dev/haunted/node_modules/.pnpm/@lexical+react@0.5.0_7x5ipar2pryb5a4en6ju6uefiq/node_
    ...
```

This is happening because `window` availability is not checked before use like this:

```typescript
const getSelection = (): Selection | null => typeof window !== 'undefined' ? window.getSelection() : null;
```

or with `CAN_USE_DOM` imported:

```typescript
const getSelection = (): Selection | null => CAN_USE_DOM ? window.getSelection() : null;
```

**Comment by chankruze** [comment]
I'm still facing this issue with Remix. Following this exmple: https://codesandbox.io/s/lexical-rich-text-example-5tncvy

![image](https://user-images.githubusercontent.com/29806845/198511516-ea559d3b-c547-42d9-8f33-1f2b19db5177.png)

```console
ReferenceError: window is not defined
    at getSelection (/home/chankruze/iconfess/node_modules/lexical/Lexical.dev.js:68:35)
    at internalCreateSelection (/home/chankruze/iconfess/node_modules/lexical/Lexical.dev.js:5028:24)
    at beginUpdate (/home/chankruze/iconfess/node_modules/lexical/Lexical.dev.js:6021:39)
    at updateEditor (/home/chankruze/iconfess/node_modules/lexical/Lexical.dev.js:6116:5)
    at LexicalEditor.update (/home/chankruze/iconfess/node_modules/lexical/Lexical.dev.js:9114:5)
    at initializeEditor (/home/chankruze/iconfess/node_modules/@lexical/react/LexicalComposer.dev.js:89:12)
    at /home/chankruze/iconfess/node_modules/@lexical/react/LexicalComposer.dev.js:66:7
    at Object.useMemo (/home/chankruze/iconfess/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5128:19)
    at Object.useMemo (/home/chankruze/iconfess/node_modules/react/cjs/react.development.js:1650:21)
    at LexicalComposer (/home/chankruze/iconfess/node_modules/@lexical/react/LexicalComposer.dev.js:46:33)
```
