### ISSUE TITLE
Bug: Sticky Note Plugin crashes Playground on import

### ISSUE THREAD

**Issue by timaxlucas** [facebook/lexical#3240]
Lexical version: 0.5.1-next.1

## Steps To Reproduce

1. Open [Playground](https://playground.lexical.dev/)
2. Create a Sticky Note
3. Export
4. Import

```
TypeError: Cannot set properties of undefined (setting 'theme')
    at LexicalNestedComposer.1647df3c.js:1:575
    at Object.useMemo (main.fa4a2c4e.js:21:69182)
    at c.useMemo (main.fa4a2c4e.js:1:8266)
    at i (LexicalNestedComposer.1647df3c.js:1:443)
    at ma (main.fa4a2c4e.js:21:62859)
    at fu (main.fa4a2c4e.js:21:119869)
    at cc (main.fa4a2c4e.js:21:108839)
    at lc (main.fa4a2c4e.js:21:108767)
    at ac (main.fa4a2c4e.js:21:108630)
    at Xu (main.fa4a2c4e.js:21:105437)
```

**Comment by timaxlucas** [comment]
Update: There are several issues with the StickyNote plugin. Thanks #3241 - this almost fixes the persistency issue.

1. StickyNode is sometimes recreated onMouseUp (when its dropped)
2. Weird behaviour of note dragging if `document.body` is scrollable.

I'll try to my best to do another PR.

**Comment by timaxlucas** [comment]
PR #3241 does fix the crash, but nested editorState isn't restored on import. PR #3246 fixes both.
