### ISSUE TITLE
Bug: Pressing backspace in front to decorator node throws an error

### ISSUE THREAD

**Issue by PSmolic** [facebook/lexical#3370]
Lexical version: 0.6.1-next.0

## Steps To Reproduce

1. Remove all content from the editor
2. Add horizontal line
3. Press arrow up
4. Press backspace three times

https://user-images.githubusercontent.com/4542049/202450551-517b0a60-eb9c-492f-bfab-1567cae99a9d.mov

This error gets thrown: 
```
App.tsx:128 Uncaught Error: Expected node root to have a parent.
    at RootNode.getParentOrThrow (LexicalNode.ts:284:26)
    at $getNearestRootOrShadowRoot (LexicalUtils.ts:1246:21)
    at RangeSelection.modify (LexicalSelection.ts:1784:20)
    at RangeSelection.deleteCharacter (LexicalSelection.ts:1855:12)
    at Array.<anonymous> (index.ts:477:19)
    at triggerCommandListeners (LexicalUpdates.ts:676:17)
    at dispatchCommand (LexicalUtils.ts:1111:10)
    at LexicalEditor.dispatchCommand (LexicalEditor.ts:692:12)
    at Array.<anonymous> (index.ts:764:23)
    at triggerCommandListeners (LexicalUpdates.ts:676:17)
```

**Comment by trueadm** [comment]
I believe this has since been fixed.
