### ISSUE TITLE
Bug: Dependencies not found with monorepo

### ISSUE THREAD

**Issue by w-ap-admin** [facebook/lexical#3513]
Lexical version: 0.5.6
Node: 19.2
React: 18.2
Yarn : 3.2.4

Hello,

I am working with a monorepo, build with `yarn 3.2.4` and `yarn workspace`.
Lexical is a workspace `@packages/lexical`. I can build a `dist ` with `tsc` or run the `lexical playground` with `vite` if i run the `yarn workspace @packages/lexical dev`.
But if I use `@packages/lexical` as dependencies of another workspace (e.g. `@services/web`) the build will faill:
```
X [ERROR] Could not resolve "@lexical/markdown"

    ../../.yarn/__virtual__/verbum-virtual-3676e88551/0/cache/verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip/node_modules/verbum/dist/verbum.esm.js:44:154:
      44 │ ...rkdownString, $convertToMarkdownString } from '@lexical/markdown';
         ╵                                                  ~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@lexical/markdown" here because it's not listed as a dependency of this package:

    ../../.pnp.cjs:23184:33:
      23184 │           "packageDependencies": [\
            ╵                                  ~~

  You can mark the path "@lexical/markdown" as external to exclude it from the bundle, which will remove this error.

X [ERROR] Could not resolve "@lexical/yjs"

    ../../.yarn/__virtual__/verbum-virtual-3676e88551/0/cache/verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip/node_modules/verbum/dist/verbum.esm.js:45:58:
      45 │ ...{ CONNECTED_COMMAND, TOGGLE_CONNECT_COMMAND } from '@lexical/yjs';
         ╵                                                       ~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@lexical/yjs" here because it's not listed as a dependency of this package:

    ../../.pnp.cjs:23184:33:
      23184 │           "packageDependencies": [\
            ╵                                  ~~

  You can mark the path "@lexical/yjs" as external to exclude it from the bundle, which will remove this error.

X [ERROR] Could not resolve "@lexical/text"

    ../../.yarn/__virtual__/verbum-virtual-3676e88551/0/cache/verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip/node_modules/verbum/dist/verbum.esm.js:48:7:
      48 │ import '@lexical/text';
         ╵        ~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@lexical/text" here because it's not listed as a dependency of this package:

    ../../.pnp.cjs:23184:33:
      23184 │           "packageDependencies": [\
            ╵                                  ~~

  You can mark the path "@lexical/text" as external to exclude it from the bundle, which will remove this error.

X [ERROR] Could not resolve "yjs"

    ../../.yarn/__virtual__/@lexical-yjs-virtual-d801aca7fa/0/cache/@lexical-yjs-npm-0.5.0-68dabf9f33-f5f1b3e897.zip/node_modules/@lexical/yjs/LexicalYjs.dev.js:10:18:
      10 │ var yjs = require('yjs');
         ╵                   ~~~~~

  The Yarn Plug'n'Play manifest says this package has a peer dependency on "yjs", but the package "yjs" has not been installed:

    ../../.pnp.cjs:5822:20:
      5822 │             ["yjs", null]\
           ╵                     ~~~~

  You can mark the path "yjs" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "@lexical/selection"

    ../../.yarn/__virtual__/@lexical-yjs-virtual-d801aca7fa/0/cache/@lexical-yjs-npm-0.5.0-68dabf9f33-f5f1b3e897.zip/node_modules/@lexical/yjs/LexicalYjs.dev.js:11:24:
      11 │ var selection = require('@lexical/selection');
         ╵                         ~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@lexical/selection" here because it's not listed as a dependency of this package:

    ../../.pnp.cjs:5816:33:
      5816 │           "packageDependencies": [\
           ╵                                  ~~

  You can mark the path "@lexical/selection" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "yjs"

    ../../.yarn/cache/y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip/node_modules/y-protocols/auth.js:2:19:
      2 │ import * as Y from 'yjs' // eslint-disable-line
        ╵                    ~~~~~

  The Yarn Plug'n'Play manifest forbids importing "yjs" here because it's not listed as a dependency of this package:

    ../../.pnp.cjs:24180:33:
      24180 │           "packageDependencies": [\
            ╵                                  ~~

  You can mark the path "yjs" as external to exclude it from the bundle, which will remove this error.

X [ERROR] Could not resolve "@lexical/clipboard"

    ../../.yarn/__virtual__/@lexical-rich-text-virtual-2ef626bc85/0/cache/@lexical-rich-text-npm-0.5.0-711e98890c-87191663fb.zip/node_modules/@lexical/rich-text/LexicalRichText.dev.js:9:24:
      9 │ var clipboard = require('@lexical/clipboard');
        ╵                         ~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest says this package has a peer dependency on "@lexical/clipboard", but the package "@lexical/clipboard" has not been installed:

    ../../.pnp.cjs:5693:35:
      5693 │             ["@lexical/clipboard", null],\
           ╵                                    ~~~~

  You can mark the path "@lexical/clipboard" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "@lexical/selection"

    ../../.yarn/__virtual__/@lexical-rich-text-virtual-2ef626bc85/0/cache/@lexical-rich-text-npm-0.5.0-711e98890c-87191663fb.zip/node_modules/@lexical/rich-text/LexicalRichText.dev.js:10:24:
      10 │ var selection = require('@lexical/selection');
         ╵                         ~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest says this package has a peer dependency on "@lexical/selection", but the package "@lexical/selection" has not been installed:

    ../../.pnp.cjs:5694:35:
      5694 │             ["@lexical/selection", null],\
           ╵                                    ~~~~

  You can mark the path "@lexical/selection" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "yjs"

    ../../.yarn/cache/y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip/node_modules/y-protocols/sync.js:7:19:
      7 │ import * as Y from 'yjs'
        ╵                    ~~~~~

  The Yarn Plug'n'Play manifest forbids importing "yjs" here because it's not listed as a dependency of this package:

    ../../.pnp.cjs:24180:33:
      24180 │           "packageDependencies": [\
            ╵                                  ~~

  You can mark the path "yjs" as external to exclude it from the bundle, which will remove this error.

X [ERROR] Could not resolve "yjs"

    ../../.yarn/cache/y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip/node_modules/y-protocols/awareness.js:11:19:
      11 │ import * as Y from 'yjs' // eslint-disable-line
         ╵                    ~~~~~

  The Yarn Plug'n'Play manifest forbids importing "yjs" here because it's not listed as a dependency of this package:

    ../../.pnp.cjs:24180:33:
      24180 │           "packageDependencies": [\
            ╵                                  ~~

  You can mark the path "yjs" as external to exclude it from the bundle, which will remove this error.

F:\dev\javascript\react\lms\.yarn\unplugged\esbuild-npm-0.15.18-61e07796c8\node_modules\esbuild\lib\main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 10 errors:
../../.yarn/__virtual__/@lexical-rich-text-virtual-2ef626bc85/0/cache/@lexical-rich-text-npm-0.5.0-711e98890c-87191663fb.zip/node_modules/@lexical/rich-text/LexicalRichText.dev.js:9:24: ERROR: Could not resolve "@lexical/clipboard"
../../.yarn/__virtual__/@lexical-rich-text-virtual-2ef626bc85/0/cache/@lexical-rich-text-npm-0.5.0-711e98890c-87191663fb.zip/node_modules/@lexical/rich-text/LexicalRichText.dev.js:10:24: ERROR: Could not resolve "@lexical/selection"
../../.yarn/__virtual__/@lexical-yjs-virtual-d801aca7fa/0/cache/@lexical-yjs-npm-0.5.0-68dabf9f33-f5f1b3e897.zip/node_modules/@lexical/yjs/LexicalYjs.dev.js:10:18: ERROR: Could not resolve "yjs"
../../.yarn/__virtual__/@lexical-yjs-virtual-d801aca7fa/0/cache/@lexical-yjs-npm-0.5.0-68dabf9f33-f5f1b3e897.zip/node_modules/@lexical/yjs/LexicalYjs.dev.js:11:24: ERROR: Could not resolve "@lexical/selection"
../../.yarn/__virtual__/verbum-virtual-3676e88551/0/cache/verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip/node_modules/verbum/dist/verbum.esm.js:44:154: ERROR: Could not resolve "@lexical/markdown"
...
    at failureErrorWithLog (F:\dev\javascript\react\lms\.yarn\unplugged\esbuild-npm-0.15.18-61e07796c8\node_modules\esbuild\lib\main.js:1575:15)
    at F:\dev\javascript\react\lms\.yarn\unplugged\esbuild-npm-0.15.18-61e07796c8\node_modules\esbuild\lib\main.js:1033:28
    at runOnEndCallbacks (F:\dev\javascript\react\lms\.yarn\unplugged\esbuild-npm-0.15.18-61e07796c8\node_modules\esbuild\lib\main.js:1447:61)
    at buildResponseToResult (F:\dev\javascript\react\lms\.yarn\unplugged\esbuild-npm-0.15.18-61e07796c8\node_modules\esbuild\lib\main.js:1031:7)
    at F:\dev\javascript\react\lms\.yarn\unplugged\esbuild-npm-0.15.18-61e07796c8\node_modules\esbuild\lib\main.js:1143:14
    at responseCallbacks.<computed> (F:\dev\javascript\react\lms\.yarn\unplugged\esbuild-npm-0.15.18-61e07796c8\node_modules\esbuild\lib\main.js:680:9)
    at handleIncomingPacket (F:\dev\javascript\react\lms\.yarn\unplugged\esbuild-npm-0.15.18-61e07796c8\node_modules\esbuild\lib\main.js:735:9)
    at Socket.readFromStdout (F:\dev\javascript\react\lms\.yarn\unplugged\esbuild-npm-0.15.18-61e07796c8\node_modules\esbuild\lib\main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 24,
        file: '../../.yarn/__virtual__/@lexical-rich-text-virtual-2ef626bc85/0/cache/@lexical-rich-text-npm-0.5.0-711e98890c-87191663fb.zip/node_modules/@lexical/rich-text/LexicalRichText.dev.js',
        length: 20,
        line: 9,
        lineText: "var clipboard = require('@lexical/clipboard');",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 35,
            file: '../../.pnp.cjs',
            length: 4,
            line: 5693,
            lineText: '            ["@lexical/clipboard", null],\\',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest says this package has a peer dependency on "@lexical/clipboard", but the package "@lexical/clipboard" has not been installed:`
        },
        {
          location: null,
          text: 'You can mark the path "@lexical/clipboard" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@lexical/clipboard"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 24,
        file: '../../.yarn/__virtual__/@lexical-rich-text-virtual-2ef626bc85/0/cache/@lexical-rich-text-npm-0.5.0-711e98890c-87191663fb.zip/node_modules/@lexical/rich-text/LexicalRichText.dev.js',
        length: 20,
        line: 10,
        lineText: "var selection = require('@lexical/selection');",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 35,
            file: '../../.pnp.cjs',
            length: 4,
            line: 5694,
            lineText: '            ["@lexical/selection", null],\\',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest says this package has a peer dependency on "@lexical/selection", but the package "@lexical/selection" has not been installed:`
        },
        {
          location: null,
          text: 'You can mark the path "@lexical/selection" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@lexical/selection"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 18,
        file: '../../.yarn/__virtual__/@lexical-yjs-virtual-d801aca7fa/0/cache/@lexical-yjs-npm-0.5.0-68dabf9f33-f5f1b3e897.zip/node_modules/@lexical/yjs/LexicalYjs.dev.js',
        length: 5,
        line: 10,
        lineText: "var yjs = require('yjs');",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 20,
            file: '../../.pnp.cjs',
            length: 4,
            line: 5822,
            lineText: '            ["yjs", null]\\',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest says this package has a peer dependency on "yjs", but the package "yjs" has not been installed:`
        },
        {
          location: null,
          text: 'You can mark the path "yjs" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "yjs"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 24,
        file: '../../.yarn/__virtual__/@lexical-yjs-virtual-d801aca7fa/0/cache/@lexical-yjs-npm-0.5.0-68dabf9f33-f5f1b3e897.zip/node_modules/@lexical/yjs/LexicalYjs.dev.js',
        length: 20,
        line: 11,
        lineText: "var selection = require('@lexical/selection');",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 33,
            file: '../../.pnp.cjs',
            length: 526,
            line: 5816,
            lineText: '          "packageDependencies": [\\',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest forbids importing "@lexical/selection" here because it's not listed as a dependency of this package:`
        },
        {
          location: null,
          text: 'You can mark the path "@lexical/selection" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@lexical/selection"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 154,
        file: '../../.yarn/__virtual__/verbum-virtual-3676e88551/0/cache/verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip/node_modules/verbum/dist/verbum.esm.js',
        length: 19,
        line: 44,
        lineText: "import { CHECK_LIST, ELEMENT_TRANSFORMERS, TEXT_FORMAT_TRANSFORMERS, TEXT_MATCH_TRANSFORMERS, $convertFromMarkdownString, $convertToMarkdownString } from '@lexical/markdown';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 33,
            file: '../../.pnp.cjs',
            length: 4098,
            line: 23184,
            lineText: '          "packageDependencies": [\\',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest forbids importing "@lexical/markdown" here because it's not listed as a dependency of this package:`
        },
        {
          location: null,
          text: 'You can mark the path "@lexical/markdown" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@lexical/markdown"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 58,
        file: '../../.yarn/__virtual__/verbum-virtual-3676e88551/0/cache/verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip/node_modules/verbum/dist/verbum.esm.js',
        length: 14,
        line: 45,
        lineText: "import { CONNECTED_COMMAND, TOGGLE_CONNECT_COMMAND } from '@lexical/yjs';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 33,
            file: '../../.pnp.cjs',
            length: 4098,
            line: 23184,
            lineText: '          "packageDependencies": [\\',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest forbids importing "@lexical/yjs" here because it's not listed as a dependency of this package:`
        },
        {
          location: null,
          text: 'You can mark the path "@lexical/yjs" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@lexical/yjs"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 7,
        file: '../../.yarn/__virtual__/verbum-virtual-3676e88551/0/cache/verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip/node_modules/verbum/dist/verbum.esm.js',
        length: 15,
        line: 48,
        lineText: "import '@lexical/text';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 33,
            file: '../../.pnp.cjs',
            length: 4098,
            line: 23184,
            lineText: '          "packageDependencies": [\\',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest forbids importing "@lexical/text" here because it's not listed as a dependency of this package:`
        },
        {
          location: null,
          text: 'You can mark the path "@lexical/text" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@lexical/text"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 19,
        file: '../../.yarn/cache/y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip/node_modules/y-protocols/auth.js',
        length: 5,
        line: 2,
        lineText: "import * as Y from 'yjs' // eslint-disable-line",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 33,
            file: '../../.pnp.cjs',
            length: 96,
            line: 24180,
            lineText: '          "packageDependencies": [\\',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest forbids importing "yjs" here because it's not listed as a dependency of this package:`
        },
        {
          location: null,
          text: 'You can mark the path "yjs" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "yjs"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 19,
        file: '../../.yarn/cache/y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip/node_modules/y-protocols/awareness.js',
        length: 5,
        line: 11,
        lineText: "import * as Y from 'yjs' // eslint-disable-line",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 33,
            file: '../../.pnp.cjs',
            length: 96,
            line: 24180,
            lineText: '          "packageDependencies": [\\',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest forbids importing "yjs" here because it's not listed as a dependency of this package:`
        },
        {
          location: null,
          text: 'You can mark the path "yjs" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "yjs"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 19,
        file: '../../.yarn/cache/y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip/node_modules/y-protocols/sync.js',
        length: 5,
        line: 7,
        lineText: "import * as Y from 'yjs'",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 33,
            file: '../../.pnp.cjs',
            length: 96,
            line: 24180,
            lineText: '          "packageDependencies": [\\',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest forbids importing "yjs" here because it's not listed as a dependency of this package:`
        },
        {
          location: null,
          text: 'You can mark the path "yjs" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "yjs"'
    }
  ],
  warnings: []
}

Node.js v19.0.1
```

There is also a warning message with the command `yarn install`:
```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @lexical/markdown@npm:0.5.0 [e8d2d] doesn't provide @lexical/clipboard (p75dd1), requested by @lexical/rich-text
➤ YN0002: │ @lexical/markdown@npm:0.5.0 [e8d2d] doesn't provide @lexical/selection (p966e9), requested by @lexical/rich-text
➤ YN0002: │ @lexical/react@npm:0.5.0 [28e30] doesn't provide yjs (p49031), requested by @lexical/yjs
➤ YN0002: │ @lexical/react@npm:0.5.0 [3676e] doesn't provide yjs (p0a562), requested by @lexical/yjs
...
➤ YN0000: Failed with errors in 1s 621ms
```

The module `@lexical/markdown` in `.yarn/cache` as `@lexical/rich-text` as a `dependencies`, and the module `@lexical/rich-text` as a `peerDependencies` on `@lexical/clipboard`, so everything seems to be fine here.

I try to build project with `react-scripts` but the problem still the same:
```
 ERROR in ../../.yarn/__virtual__/@lexical-yjs-virtual-d801aca7fa/0/cache/@lexical-yjs-npm-0.5.0-68dabf9f33-f5f1b3e897.zip/node_modules/@lexical/yjs/LexicalYjs.dev.js 11:16-45
➤ YN0000: [@services/web]: Module not found: Error: Can't resolve '@lexical/selection' in 'F:\dev\javascript\react\lms\.yarn\__virtual__\@lexical-yjs-virtual-d801aca7fa\0\cache\@lexical-yjs-npm-0.5.0-68dabf9f33-f5f1b3e897.zip\node_modules\@lexical\yjs'
➤ YN0000: [@services/web]:
➤ YN0000: [@services/web]: ERROR in ../../.yarn/__virtual__/verbum-virtual-3676e88551/0/cache/verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip/node_modules/verbum/dist/verbum.esm.js 44:0-174
➤ YN0000: [@services/web]: Module not found: Error: Can't resolve '@lexical/markdown' in 'F:\dev\javascript\react\lms\.yarn\__virtual__\verbum-virtual-3676e88551\0\cache\verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip\node_modules\verbum\dist'
➤ YN0000: [@services/web]:
➤ YN0000: [@services/web]: ERROR in ../../.yarn/__virtual__/verbum-virtual-3676e88551/0/cache/verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip/node_modules/verbum/dist/verbum.esm.js 45:0-73
➤ YN0000: [@services/web]: Module not found: Error: Can't resolve '@lexical/yjs' in 'F:\dev\javascript\react\lms\.yarn\__virtual__\verbum-virtual-3676e88551\0\cache\verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip\node_modules\verbum\dist'
➤ YN0000: [@services/web]:
➤ YN0000: [@services/web]: ERROR in ../../.yarn/__virtual__/verbum-virtual-3676e88551/0/cache/verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip/node_modules/verbum/dist/verbum.esm.js 48:0-23
➤ YN0000: [@services/web]: Module not found: Error: Can't resolve '@lexical/text' in 'F:\dev\javascript\react\lms\.yarn\__virtual__\verbum-virtual-3676e88551\0\cache\verbum-npm-0.4.1-97e7d7432e-1c2085b7d0.zip\node_modules\verbum\dist'
➤ YN0000: [@services/web]:
➤ YN0000: [@services/web]: ERROR in ../../.yarn/cache/y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip/node_modules/y-protocols/auth.js 1:0-25
➤ YN0000: [@services/web]: Module not found: Error: Can't resolve 'yjs' in 'F:\dev\javascript\react\lms\.yarn\cache\y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip\node_modules\y-protocols'
➤ YN0000: [@services/web]:
➤ YN0000: [@services/web]: ERROR in ../../.yarn/cache/y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip/node_modules/y-protocols/awareness.js 11:0-25
➤ YN0000: [@services/web]: Module not found: Error: Can't resolve 'yjs' in 'F:\dev\javascript\react\lms\.yarn\cache\y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip\node_modules\y-protocols'
➤ YN0000: [@services/web]:
➤ YN0000: [@services/web]: ERROR in ../../.yarn/cache/y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip/node_modules/y-protocols/sync.js 7:0-25
➤ YN0000: [@services/web]: Module not found: Error: Can't resolve 'yjs' in 'F:\dev\javascript\react\lms\.yarn\cache\y-protocols-npm-1.0.5-af6f64b4df-d19404a4eb.zip\node_modules\y-protocols'
```

**Comment by nzhiti** [comment]
Same here in monorepo using Yarn plug and play

**Comment by trueadm** [comment]
Our repository doesn't support Yarn (we used to use it but we ran into far too many problems and it didn't play nicely with our CI). You'll like have to use npm instead.
