### ISSUE TITLE
Bug: insertNodes does not allow for insertion on root

### ISSUE THREAD

**Issue by yaman3bd** [facebook/lexical#3606]
I was trying to add the editor default value from HTML
I tried to make a plugin for this but did not work as accepted
so I tried to append to the editor state:
`defaultValue` passed as prop to the editor
```ts
const update = (editor: LexicalEditor) => {
      const parser = new DOMParser();
      const dom = parser.parseFromString(defaultValue ?? '', 'text/html');

      const nodes = $generateNodesFromDOM(editor, dom);

      $getRoot().select();

      $insertNodes(nodes);
};
const initialConfig = {
      editorState: update,
      namespace: 'Playground',
      nodes: [...DefaultNodes],
      onError: (error: Error) => {
        throw error;
      },
      theme: DefaultTheme
};
```
but I get this error:
```
Editor.tsx:87 Uncaught Error: replace: cannot be called on root nodes
    at RootNode.replace (Lexical.dev.js:7826:13)
    at RangeSelection.insertNodes (Lexical.dev.js:4304:20)
    at $insertNodes (Lexical.dev.js:5668:20)
    at update (Editor.tsx:80:7)
    at LexicalComposer.dev.js:123:15
    at beginUpdate (Lexical.dev.js:6322:5)
    at updateEditor (Lexical.dev.js:6413:5)
    at LexicalEditor.update (Lexical.dev.js:9480:5)
    at initializeEditor (LexicalComposer.dev.js:119:18)
    at LexicalComposer.dev.js:66:7
```
so I tried to change the update method to:
```ts
const update = (editor: LexicalEditor) => {
      console.log('test');
      const parser = new DOMParser();
      const dom = parser.parseFromString(defaultValue ?? "", "text/html");

      const nodes = $generateNodesFromDOM(editor, dom);
      const root = $getRoot();
      root.append(...nodes);
};
```
it worked without any error

Lexical version:
`"lexical": "^0.6.0",`
## Steps To Reproduce

1. try to append the editor state HTML string not Json nodes
2. clone the repo.
3. `npm install`
4. `npm run dev`
5. open the console and the error shows up

Link to code example:
here is the github repo like:
[https://github.com/yaman3bd/lexical-default-value-example](https://github.com/yaman3bd/lexical-default-value-example)

**Comment by chalecki** [comment]
I think I faced the same issue with the content that includes solo-flying text nodes (text not wrapped without any `<p>` or `<span>` parent tag). 

I create a custom plugin for setting initial HTML, maybe it will solve your problem

```tsx
export const SetInitialHTMLPlugin: React.FC<{ initHtml?: string }> = ({ initHtml }) => {
  const [editor] = useLexicalComposerContext();

  useEffect(() => {
    editor.update(() => {
      const currentHtmlContent = $generateHtmlFromNodes(editor, null);

      if (initHtml && currentHtmlContent !== initHtml && !editor.isComposing()) {
        const parser = new DOMParser();
        const dom = parser.parseFromString(initHtml, 'text/html');
        const nodes = $generateNodesFromDOM(editor, dom);

        // 👇 wrap all text nodes with paragraph node
        const validNodesToInsert = nodes.map(node => {
          const paragraphNode= $createParagraphNode();

          if (node.getType() === 'text') {
            paragraphNode.append(node);
            return paragraphNode;
          } else {
            return node;
          }
        });

        const root = $getRoot();
        root.clear();
        root.append(...validNodesToInsert);
        $setSelection(null);

        editor.dispatchCommand(CLEAR_HISTORY_COMMAND, void 0);
      }
    });
  }, [editor, initHtml]);

  return null;
};
```

**Comment by Iuriy-Budnikov** [comment]
I have the same issue with HTML to Lexilal. Do we have some official playground example?

**Comment by Iuriy-Budnikov** [comment]
Does it support controllable value?

**Comment by chalecki** [comment]
> Does it support controllable value?

Could you be more specific? What does "it" refers to? And what do you mean by *controllable* value?

**Comment by Iuriy-Budnikov** [comment]
> 

Yes, controllable value. Because it's a basic feature for any input component

**Comment by yaman3bd** [comment]
> I think I faced the same issue with the content that includes solo-flying text nodes (text not wrapped without any `<p>` or `<span>` parent tag).
> 
hey, @chalecki thanks for the idea,
but I have solved the issue different approach by appending the editor state in the config:
```ts
const updateHTML = (editor: LexicalEditor, value: string, clear: boolean) => {
      const root = $getRoot();
      const parser = new DOMParser();
      const dom = parser.parseFromString(isNonHtml(value) ? `<p>${value}</p>` : value, "text/html");
      const nodes = $generateNodesFromDOM(editor, dom);
      if (clear) {
        root.clear();
      }
      root.append(...nodes);
    };

    const prepopulatedRichText = (editor: LexicalEditor) => {
      if (!defaultValue) return undefined;
      updateHTML(editor, defaultValue ?? "", true);
    };

    const initialConfig = {
      editorState: prepopulatedRichText,
      namespace: "Playground",
      nodes: [...DefaultNodes],
      onError: (error: Error) => {
        throw error;
      },
      theme: DefaultTheme
    };
```
and then also made a plugin for setting the default value if its a controlled value:
I have the `updateHTML` method duplicated because I will refactor the code later
```ts
export default function LexicalDefaultValuePlugin({ value = "" }: { value?: string | null }) {
  const [editor] = useLexicalComposerContext();

  const updateHTML = (editor: LexicalEditor, value: string, clear: boolean) => {
    const root = $getRoot();
    const parser = new DOMParser();
    const dom = parser.parseFromString(isNonHtml(value) ? `<p>${value}</p>` : value, "text/html");
    const nodes = $generateNodesFromDOM(editor, dom);
    if (clear) {
      root.clear();
    }
    root.append(...nodes);
  };

  useEffect(() => {
    if (editor && value) {
      editor.update(() => {
        updateHTML(editor, value, true);
      });
    }
  }, [value]);

  return null;
}
```
and if the value was a solo-flying text I did  `<p>${value}</p>` only wrap the complete value

**Comment by yaman3bd** [comment]
> Does it support controllable value?

@Iuriy-Budnikov both solutions that I posted or @chalecki posted support  controllable value because basically the plugin watching the value changes in  `useEffect`

**Comment by chalecki** [comment]
> @yaman3bd it doesn't work well for me. The editor is losing focus on any change

Share some code with us :) what you've used
