### ISSUE TITLE
Bug: CollaborationPlugin is not compatible with NextJS

### ISSUE THREAD

**Issue by 6peterlu** [facebook/lexical#3659]
Lexical version: 0.7.5

## Steps To Reproduce

1. Add CollaborationPlugin to a LexicalComposer in a NextJS project.
2. Deploy NextJS Project via Vercel
3. Attempt to open a view that renders the LexicalComposer.

## The current behavior
This error is shown in console:
```
ReferenceError: Cannot access 'C' before initialization
    at Object.QP (Skip.js:60:1)
    at 6292 (YArray.js:45:29)
    at l (bootstrap:21:1)
    at 8697 (ContentString.js:112:8)
    at l (bootstrap:21:1)
    at 8535 (Skip.js:60:1)
    at l (bootstrap:21:1)
    at 5021 (DeleteSet.js:325:1)
    at l (bootstrap:21:1)
    at 3838 (StructStore.js:261:5)
```

## The expected behavior
No error.

I should also note that things work locally, I believe `next build` is where it breaks. But I am not sure about that.

**Comment by 6peterlu** [comment]
I think this may actually be an issue in yjs or y-websocket, I will file an issue in y-websocket.
