### ISSUE TITLE
Bug: isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`

### ISSUE THREAD

**Issue by moyang-pro** [facebook/lexical#3974]
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (~\packages\lexical\node_modules\@babel\types\lib\validators\generated\index.js:3940:35)
    at NodePath.<computed> [as isModuleDeclaration] (~\packages\lexical\node_modules\@babel\traverse\lib\path\index.js:239:12)
>npm -v
9.5.1

>node -v
v16.18.0

**Comment by acywatson** [comment]
Not enough info - please use the issue templates.

**Comment by moyang-pro** [comment]
thank,it is ok
