### ISSUE TITLE
Bug: Element type is invalid error when trying to insert a horizontal rule node in a rich text editor setup

### ISSUE THREAD

**Issue by wingedrasengan927** [facebook/lexical#4195]
Getting the following error when trying to insert a `HorizontalRuleNode` in a rich text editor setup:
```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `RichTextPlugin`.
    at createFiberFromTypeAndProps (react-dom.development.js:28439:1)
    at createFiberFromElement (react-dom.development.js:28465:1)
    at reconcileSingleElement (react-dom.development.js:15750:1)
    at reconcileChildFibers (react-dom.development.js:15808:1)
    at updatePortalComponent (react-dom.development.js:21101:1)
    at beginWork (react-dom.development.js:21627:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
```

Lexical version: 0.9.1

## Steps To Reproduce
`Editor.js` file.
```
import { LexicalComposer } from "@lexical/react/LexicalComposer";
import { RichTextPlugin } from "@lexical/react/LexicalRichTextPlugin";
import { ContentEditable } from "@lexical/react/LexicalContentEditable";
import TestPlugin from "./plugins/TestPlugin";
import { HorizontalRuleNode } from "@lexical/react/LexicalHorizontalRuleNode";

export default function Editor() {
    const initialConfig = {
        namespace: "MyEditor",
        onError(error) {
            throw error;
        },
        nodes: [HorizontalRuleNode],
    };

    return (
        <LexicalComposer initialConfig={initialConfig}>
            <div className="editor-container">
                <div className="editor-inner">
                    <RichTextPlugin
                        contentEditable={
                            <ContentEditable className="editor-input" />
                        }
                    />
                    <TestPlugin />
                </div>
            </div>
        </LexicalComposer>
    );
}
```

`TestPlugin.js`
```
import { $getRoot } from "lexical";
import { $createHorizontalRuleNode } from "@lexical/react/LexicalHorizontalRuleNode";
import { useLexicalComposerContext } from "@lexical/react/LexicalComposerContext";

export default function TestPlugin() {
    const [editor] = useLexicalComposerContext();

    editor.update(() => {
        // Get the RootNode from the EditorState
        const root = $getRoot();
        const rule = $createHorizontalRuleNode();
        root.append(rule);
    });

    return null;
}

```

**Comment by arantespp** [comment]
I'm also getting a error with horizontal rule. In my case, it renders with an error ([link to reproduce](https://storybook.tereza.tech/?path=/story/components-editor--empty), just type "---"). My code: [Editor.tsx](https://github.com/terezatech/tereza-tech/blob/main/packages/components/src/components/Editor/Editor.tsx) and [HorizontalRulePlugin.tsx](https://github.com/terezatech/tereza-tech/blob/main/packages/components/src/components/Editor/HorizontalRulePlugin.tsx)

![image](https://user-images.githubusercontent.com/16626980/227815825-7bb5f72f-0223-4052-9e8c-641384043179.png)

**Comment by arantespp** [comment]
It's now working after adding `LexicalErrorBoundary` ([PR](https://github.com/terezatech/tereza-tech/pull/70/files#diff-96b804363f4958f6ecfc0e715a00b4b84cf8c98dcd57f43dddb4be7293442f6b) to `RichTextPlugin`.

**Comment by wingedrasengan927** [comment]
Working for me as well. Thanks a lot!

**Comment by muxuhang** [comment]
<RichTextPlugin
  ErrorBoundary={LexicalErrorBoundary}
      contentEditable={
          <ContentEditable className="editor-input" />
      }
  />

**Comment by jnoahjohnson** [comment]
I am getting that same error even with the ErrorBoundary. On version `0.14.3`
