### ISSUE TITLE
Bug: Crash when deleting a table row in a table with merged cells

### ISSUE THREAD

**Issue by michaelsoultanidis** [facebook/lexical#4377]
Deleting a row of a table that contains merged cells fails with a crash.

Lexical version: 0.10.0 (Latest)

## Steps To Reproduce

1. Create a 4x4 table (**not the experimental**) in the Lexical Playground.  
2. Merge cells (crash is consistently reproducible by merging cells as shown in the video)
3. Add two new rows at the end of the table
4. Try to remove them

Stack trace:
```
caught Error: Minified Lexical error #114; visit https://lexical.dev/docs/error?code=114 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ld (main.7d82f19f.js:21:129552)
    at ed.DEPRECATED_$getNodeTriplet (main.7d82f19f.js:21:216805)
    at Lj.$deleteTableRow__EXPERIMENTAL (main.7d82f19f.js:21:427956)
    at main.7d82f19f.js:21:1215511
    at eh (main.7d82f19f.js:21:189954)
    at th (main.7d82f19f.js:21:192095)
    at Dh.update (main.7d82f19f.js:21:213339)
    at main.7d82f19f.js:21:1215498
    at onClick (main.7d82f19f.js:21:1218228)
    at Object.Ct (main.7d82f19f.js:21:16658)
L
```

https://user-images.githubusercontent.com/88332746/233639948-201a0f24-765d-4633-b6cb-b401a217a26f.mov

**Comment by icrosil** [comment]
Looking 👀
