### ISSUE TITLE
Bug: Unable to find an active editor. This method can only be used synchronously during the callback of editor.update().

### ISSUE THREAD

**Issue by lwelcom** [facebook/lexical#5137]
Lexical version:

## Steps To Reproduce

1.
2.

Link to code example:

 const initialState = () => {
  //  console.log(editor, "------------------editor");
    const paragraph = $createParagraphNode();
    const text = $createTextNode('Hello World22!');
    paragraph.append(text);
    const root = $getRoot();
    root.append(paragraph);
    root.selectEnd();
};

  <EditorComposer initialEditorState={initialState}>

 </EditorComposer>

**Comment by lwelcom** [comment]
<EditorComposer initialEditorState={initialState}>
</EditorComposer>   

question：
1. Unable to initialize default value 2. onChange cannot be converted into html code

**Comment by lwelcom** [comment]
For example：
https://lightrun.com/answers/facebook-lexical-bug-syncyjschangestolexical-unable-to-find-active-editor-in-headless-mode

ERROR
Unable to find an active editor. This method can only be used synchronously during the callback of editor.update().
    at getActiveEditor (http://localhost:3000/static/js/vendors-node_modules_lexical_html_LexicalHtml_js-node_modules_lexical_react_LexicalComposerCo-c0b67b.chunk.js:9592:13)
    at $setNodeKey (http://localhost:3000/static/js/vendors-node_modules_lexical_html_LexicalHtml_js-node_modules_lexical_react_LexicalComposerCo-c0b67b.chunk.js:2460:18)
    at new LexicalNode (http://localhost:3000/static/js/vendors-node_modules_lexical_html_LexicalHtml_js-node_modules_lexical_react_LexicalComposerCo-c0b67b.chunk.js:4988:5)

**Comment by petross3530mx** [comment]
[https://lightrun.com/] Is not a website which is public for everyone. Almost nobody will get your problem
