### ISSUE TITLE
Several react apps at the same page with causing error unable to find an active editor state

### ISSUE THREAD

**Issue by deven-solutions** [facebook/lexical#5224]
The problem occur when several react apps with editors are used at the same page.

The first react app that is getting focus works as expected no matter which app it is, but as soon as another app is getting focus an error occur that lexical is unable to find an active editor state. The first app editor is still working as excepted (sometimes).

Lexical version: 0.10.0

`Uncaught Error: Unable to find an active editor state. State helpers or node methods can only be used synchronously during the callback of editor.update() or editorState.read().
    at getActiveEditorState (Lexical.dev.js:7379:1)
    at $getNodeByKey (Lexical.dev.js:721:1)
    at ParagraphNode.getLatest (Lexical.dev.js:4090:1)
    at ParagraphNode.getParent (Lexical.dev.js:3690:1)
    at ParagraphNode.getIndexWithinParent (Lexical.dev.js:3664:1)
    at internalResolveSelectionPoint (Lexical.dev.js:6682:1)
    at internalResolveSelectionPoints (Lexical.dev.js:6787:1)
    at internalCreateRangeSelection (Lexical.dev.js:6898:1)
    at internalCreateSelection (Lexical.dev.js:6851:1)
    at beginUpdate (Lexical.dev.js:8008:1)`

**Comment by acywatson** [comment]
Do you have any ideas for how to repro this?

We have multiple editors all over the place without this issue, so I'm not sure what config you might have that could be causing this.

**Comment by deven-solutions** [comment]
Lexical source is included for each app,  could this be a problem? We currently have no way to share libraries between apps in the CMS. We are using webpack bundler.
