### ISSUE TITLE
Bug: build prerelease on macOS

### ISSUE THREAD

**Issue by johnnyoshika** [facebook/lexical#5420]
Lexical version: 0.12.5
OS: macOS Sonoma 14.2 (Apple Silicon M2)

## Steps To Reproduce

1. Run `npm run build-release` at the root of this project

Link to code example: not applicable

## The current behavior

Running `npm run build-release` results in:

```
> node scripts/build.js --prod --release

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at spawn (node:child_process:761:9)
    at Compiler.run (/Users/johnny/projects/lexical/lexical/node_modules/@ampproject/rollup-plugin-closure-compiler/node_modules/google-closure-compiler/lib/node/closure-compiler.js:76:26)
    at /Users/johnny/projects/lexical/lexical/node_modules/@ampproject/rollup-plugin-closure-compiler/dist/index.js:1564:18
    at new Promise (<anonymous>)
    at compiler (/Users/johnny/projects/lexical/lexical/node_modules/@ampproject/rollup-plugin-closure-compiler/dist/index.js:1554:12)
    at Object.renderChunk (/Users/johnny/projects/lexical/lexical/node_modules/@ampproject/rollup-plugin-closure-compiler/dist/index.js:1837:33)
    at async Chunk.render (/Users/johnny/projects/lexical/lexical/node_modules/rollup/dist/shared/rollup.js:15005:20)
    at async /Users/johnny/projects/lexical/lexical/node_modules/rollup/dist/shared/rollup.js:16132:40
    at async Promise.all (index 0) {
  errno: -86,
  code: 'PLUGIN_ERROR',
  syscall: 'spawn',
  pluginCode: 'Unknown system error -86',
  plugin: 'closure-compiler',
  hook: 'renderChunk'
}
```

## The expected behavior

`dist` folders to be generated as described [here](https://github.com/facebook/lexical/issues/3896#issuecomment-1429593096) and [here](https://github.com/facebook/lexical/issues/3958#issue-1596671396).

**Comment by acywatson** [comment]
Weird - thanks for reporting. Might be time for a gcc upgrade.

**Comment by etrepum** [comment]
Can't repro
