### ISSUE TITLE
Bug: fails to compile on nextjs Client Component SSR - Error: Element type is invalid: expected a string

### ISSUE THREAD

**Issue by 2wheeh** [facebook/lexical#5823]
Lexical version: 0.14.3

## Steps To Reproduce

1. clone https://github.com/2wheeh/nextjs-lexical-build-error
2. try build (or compile dynamic route pages by accessing `localhost:3000/not-work/hi`)

Link to code example: https://github.com/2wheeh/nextjs-lexical-build-error

## The current behavior

Call apis or anything imported from Lexical in **_ClientComponent_** (with `'use client'` directive).
Rendering this component in nextjs server side fails.

```ts
// client-component.tsx
'use client';

import { COMMAND_PRIORITY_CRITICAL } from 'lexical'; // just a simple constant. 

export default function ClientComponent() {
  COMMAND_PRIORITY_CRITICAL;

  return <>hi</>;
}
```

```ts
// not-work/page.tsx
import ClientComponent from '../client-component';

export default function Page() {
  return <ClientComponent />;
}
```

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

build time: fails to generate static pages.

<img width="1075" alt="image" src="https://github.com/facebook/lexical/assets/40269597/c6d7a5d4-b02e-4032-91d5-1498c2a8d4e6">

run time: fails to compile dynamic ssr pages.

<img width="1094" alt="image" src="https://github.com/facebook/lexical/assets/40269597/f5eaa8f4-3ed8-452e-ae04-15d589ce539d">

Now It only works with dynamic imports with no ssr.
```ts
// work/page.tsx
import dynamic from 'next/dynamic';

const ClientComponent = dynamic(() => import('../client-component'), { ssr: false });

export default function Page() {
  return <ClientComponent />;
}
```

## The expected behavior

works well as it was til 0.14.2

**Comment by etrepum** [comment]
Looking into it, so far I have no idea what's going on with webpack/swc here. All of the errors are very ugly and happen after a lot of compilation has already taken place.

**Comment by etrepum** [comment]
<details>
<summary>For reference, here's what the stack trace looks like in the project I've reproduced this in</summary>

```
⨯ Internal error: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:43579)
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:43309)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at aC (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50458)
    at /Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:38912
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:39398)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at aC (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50458)
    at ak (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49564)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46881)
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:41912)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at av (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7809)
    at /Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:12972
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13009)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at as (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7390)
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10825)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at av (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7809)
    at /Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:12972
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13009)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at as (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7390)
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10825)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at av (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7809)
    at /Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:12972
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13009)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:39541)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at av (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7809)
    at /Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:12972
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13009)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:39541)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at av (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7809)
    at /Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:12972
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13009)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at as (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7390)
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10825)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at av (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7809)
    at /Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:12972
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13009)
    at aS (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46552)
    at ab (/Users/bob/src/lexical-esm-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:39541)
```

</details>

**Comment by 2wheeh** [comment]
> All of the errors are very ugly and happen after a lot of compilation has already taken place.

yes indeed ! Thank you for taking time..

Just found out `next@canary` and containing `lexical` modules in [serverComponentsExternalPackages](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages) fix this errors with yarn but still errors with npm.

I'm looking into what makes this happens but so many to read...

**Comment by 2wheeh** [comment]
may be related to https://github.com/vercel/next.js/issues/62763 or some more issues in their repo
