### ISSUE TITLE
Bug: $getSelection always returns null.

### ISSUE THREAD

**Issue by kamalbilal** [facebook/lexical#6013]
Lexical version: 0.14.5
Nextjs version: 14.2.3

## I need help, maybe I'm doing something wrong.

1) I am using **LexicalPlainTextPlugin**
2) I am creating a emoji plugin that inserts emoji image in the editor.

## Reference Video:
https://drive.google.com/file/d/18AXgSl8XKf3qsXfXJIa-bIGisadfhjST/view?usp=sharing

## My emoji node:
```typescript
import { Noto_Emoji_Font } from "@/lib/fonts/fontConfig";
import { $applyNodeReplacement, DOMConversionMap, DOMConversionOutput, EditorConfig, ElementNode, LexicalNode, NodeKey, SerializedElementNode, SerializedTextNode, Spread, TextNode, isHTMLElement } from "lexical";

interface EmojiNodeInterface {
  emojiUnifiedCode: string;
  emojiText: string;
  className?: string;
}

export type SerializedEmojiNode = Spread<EmojiNodeInterface, SerializedTextNode>;

export class EmojiNode extends TextNode {
  __className;
  __emojiUrl;
  __emojiUnifiedCode;
  __emojiText;

  static getType() {
    return "custom-emoji";
  }

  static clone(node: EmojiNode): EmojiNode {
    return new EmojiNode(
      { emojiText: node.__emojiText, emojiUnifiedCode: node.__emojiUnifiedCode, className: node.__className },
      node.__key
    );
  }

  constructor(attributes: EmojiNodeInterface, key?: NodeKey) {
    const { emojiText, emojiUnifiedCode, className } = attributes;
    super(emojiText, key);
    if(className) {
      this.__className = className;
    }
    this.__emojiUnifiedCode = emojiUnifiedCode;
    this.__emojiUrl = `/images/emojis-images/${emojiUnifiedCode}.png`;
    this.__emojiText = emojiText;
  }

  createDOM(config: EditorConfig): HTMLSpanElement {
    const span = document.createElement("span");
    span.innerText = this.__emojiText;

    span.setAttribute("data-emoji-text", this.__emojiText)
    span.setAttribute("data-emoji-unified", this.__emojiUnifiedCode)

    span.classList.add("editor-emoji");
    span.classList.add("editor-emoji-inner");
    if(this.__className) {
      span.classList.add(this.__className);
    }
    span.classList.add(Noto_Emoji_Font.className);
    span.style.backgroundImage = `url("${this.__emojiUrl}")`;
    span.style.backgroundRepeat = `no-repeat`;
    span.style.display = `inline`;
    span.style.color = `transparent`;
    span.style.caretColor = `black`;
    span.style.backgroundSize = `contain`;
    span.style.padding = `0px 0px`;
    span.style.letterSpacing = `1.5px`;
    span.style.verticalAlign = `top`;
    span.style.fontSize = `1.5rem`;
    return span;
  }

  updateDOM(prevNode: EmojiNode, spanNode: HTMLSpanElement, config: EditorConfig) {
    const emojiUnifiedCode = this.__emojiUrl;

    if (prevNode.__emojiUrl !== emojiUnifiedCode) {
      return true;
    }
    return false;
  }

  static importJSON(serializedNode: SerializedEmojiNode): EmojiNode {
    return new EmojiNode({emojiText: serializedNode.emojiText, emojiUnifiedCode: serializedNode.emojiUnifiedCode, className: serializedNode.className});
  }

  exportJSON() : SerializedEmojiNode {
    return {
      ...super.exportJSON(),
      className: this.getClassName(),
      emojiText: this.getEmojiText(),
      emojiUnifiedCode: this.getemojiUnifiedCode(),
      type: "custom-emoji",
      version: 1,
    };
  }

  isTextEntity(): true {
    return true;
  }

  static importDOM(): DOMConversionMap | null {
    return {
      span: (node: Node) => ({
        conversion: convertEmojiElement,
        priority: 1,
      }),
    };
  }

  canInsertTextBefore(): false {
    return false;
  }

  isInline(): true {
    return true;
  }

  canInsertTextAfter(): false {
    return false;
  }

  getemojiUnifiedCode() {
    const self = this.getLatest();
    return self.__emojiUnifiedCode;
  }
  
  getEmojiText() {
    const self = this.getLatest();
    return self.__emojiText;
  }

  getClassName() {
    const self = this.getLatest();
    return self.__className;
  }
}

function convertEmojiElement(domNode: Node): DOMConversionOutput {
  let node = null;
  if (isHTMLSpanElement(domNode)) {
    const content = domNode.textContent;
    console.log(content);
    
    const emojiText = domNode.getAttribute("data-emoji-text");
    const emojiUnifiedCode = domNode.getAttribute("data-emoji-unified");
    if ((content !== null && content !== '') || domNode.children.length > 0 && emojiText && emojiUnifiedCode) {
      if(emojiText && emojiUnifiedCode) {
        node = $createEmojiNode({
          emojiText: emojiText,
          emojiUnifiedCode: emojiUnifiedCode
        });
      }
    }
  }
  return {node}
}

export function $isEmojiNode(node: LexicalNode | null | undefined): node is EmojiNode {
  return node instanceof EmojiNode;
}

export function $createEmojiNode(attributes: EmojiNodeInterface) {
  const node = new EmojiNode(attributes).setMode('token');
  return $applyNodeReplacement(node);
}

export function isHTMLSpanElement(x: Node): x is HTMLSpanElement {
  return isHTMLElement(x) && x.tagName === 'SPAN';
}
```
## My Emoji Plugin:
```javascript
import React, { useState } from "react";
import { BsEmojiSmileFill } from "react-icons/bs";
import CustomPopover from "../../../../antd/CustomPopover/CustomPopover";
import DropdownBottomArrow from "../../../../components/dropdowns/DropdownBottomArrow";
import styles from "./EmojiPlugin.module.css";
import cn from "classnames";
import { useLexicalComposerContext } from "@lexical/react/LexicalComposerContext";
import { $getSelection, $insertNodes } from "lexical";
import { $createEmojiNode } from "../../Nodes/EmojiNode";

const EmojiPlugin2 = () => {
  const [editor] = useLexicalComposerContext();
  const [showEmojiModal, setShowEmojiModal] = useState(false);  

  function onEmojiIconClick(emoji) {
    console.log(emoji);
    editor.update(() => {
        appendEmoji(emoji?.native, emoji.unified);
    });
  }

  function appendEmoji(nativeEmoji, emojiUnifiedCode) {
    const emojiNode = $createEmojiNode({
      emojiText: nativeEmoji,
      emojiUnifiedCode: emojiUnifiedCode,
      className: "emoji",
    });
  
    const selection = $getSelection();
    console.log(selection); // This Selection always returns null.
    if (selection?.getTextContent()) {
      selection.insertNodes([emojiNode]);
    } else {
      $insertNodes([emojiNode]);
    }
  }

  const content = <DropdownBottomArrow hideOnClick={false} className="emoji-dialog" onEmojiSelectFunc={onEmojiIconClick} />;

  return (
    // This is a antd Popover component
    <CustomPopover
      open={showEmojiModal}
      onOpenChange={(visible) => {
        if (visible) {
          editor?.focus();
        }
      }}
      content={content}
      trigger={"click"}
      showOnlyContentData
      placement="topLeft"
      autoAdjustOverflow={false}
    >
      <button
        className={cn("editor-emoji-btn", styles.button)}
        role="button"
        tabIndex={0}
        onKeyUp={(event) => {
          if (event.key === "Enter") {
            event.target.click();
          }
        }}
        onClick={() => {
          setShowEmojiModal((prev) => !prev);
        }}
        disabled={false}
      >
        <BsEmojiSmileFill />
      </button>
    </CustomPopover>
  );
};

export default EmojiPlugin2;

```
## The current behavior
1) When I open emoji dialog and click on a emoji - it successfully inserts in the editor.
2) When I select some emojis inside the editor, then opens the emoji dialog again and click on an emoji, inside the function **appendEmoji**, I am getting **$getSelection() as "null"** instead of a RangeSelection (refer to the code below).
```typescript
 function appendEmoji(nativeEmoji, emojiUnifiedCode) {
    const emojiNode = $createEmojiNode({
      emojiText: nativeEmoji,
      emojiUnifiedCode: emojiUnifiedCode,
      className: "emoji",
    });
 
    const selection = $getSelection();
    console.log(selection); // This Selection always returns null.
    
    if (selection?.getTextContent()) {
      selection.insertNodes([emojiNode]);
    } else {
      $insertNodes([emojiNode]);
    }
  }
```

3) Also after selection when I click on emoji then browser gets stuck for few seconds and then I get this error.
```javascript
app-index.tsx:25 
 RangeError: Map maximum size exceeded
    at Map.set (<anonymous>)
    at $setNodeKey (Lexical.dev.mjs:630:1)
    at new LexicalNode (Lexical.dev.mjs:3272:1)
    at new ElementNode (Lexical.dev.mjs:8116:1)
    at new ParagraphNode (Lexical.dev.mjs:8763:1)
    at $createParagraphNode (Lexical.dev.mjs:8896:1)
    at splitNodeAtPoint (Lexical.dev.mjs:7340:1)
    at removeTextAndSplitBlock (Lexical.dev.mjs:7333:1)
    at RangeSelection.insertNodes (Lexical.dev.mjs:6290:1)
    at $insertNodes (Lexical.dev.mjs:7316:1)
    at appendEmoji (EmojiPlugin2.js:34:19)
    at eval (EmojiPlugin2.js:18:9)
    at beginUpdate (Lexical.dev.mjs:7978:1)
    at updateEditor (Lexical.dev.mjs:8054:1)
    at LexicalEditor.update (Lexical.dev.mjs:9587:1)
    at Object.onEmojiIconClick [as onEmojiSelect] (EmojiPlugin2.js:17:12)
    at $89bd6bb200cc8fef$export$2e2bcd8739ae039.handleEmojiClick (module.js:2294:1)
    at Object.onClick [as clickfalse] (module.js:2405:1)
    at HTMLButtonElement.$fb96b826c0c5f37a$var$I (module.js:152:1)
```

## The expected behavior

The behavior I want is that when I select some emojis and open the emoji dialog, then click on an emoji, I want to replace the selected emojis with the newly clicked emoji.

## Reference Video:
https://drive.google.com/file/d/18AXgSl8XKf3qsXfXJIa-bIGisadfhjST/view?usp=sharing

**Comment by StyleT** [comment]
Hi! 

Pls provide https://stackblitz.com/ demo of your issue with clear steps to reproduce. You can base it on https://stackblitz.com/github/facebook/lexical/tree/main/examples/vanilla-js-plugin?file=src%2Femoji-plugin%2FEmojiPlugin.ts

Additionally pls refer to the https://lexical.dev/docs/getting-started/creating-plugin that actually creates Emoji plugin for Lexical :)
