### ISSUE TITLE
Bug: Styles of pre-populated text in editorState is not applied + Error while upgrading to version 0.14.3 or higher

### ISSUE THREAD

**Issue by amit-toren** [facebook/lexical#6030]
I'll describe two issues I have with the lexical editor:

### 1. Styles not applied - Lexical version: 0.14.2:
I'm trying to pre-populate the editor with the following stylized HTML:
```
<br>
<div style="color: #ff0000">
    <p>
        The following text is in a blockqoute tag:
    </p>
    <blockqoute style="margin: 0px 0px 0px 0.8ex; border-left: 1px solid rgb(204, 204, 204); padding-left: 1ex">
        blockqoute text!
    </blockqoute>
</div>
```

Here is the editor code:
```
function prepopulatedRichText(params: {
  value: string;
  format: Props["format"];
  editor: LexicalEditor;
}) {
  return params.editor.update(() => {
    const root = $getRoot();

    switch (params.format) {
      case "html": {
        const document = new DOMParser().parseFromString(params.value, "text/html");
        const generatedNodes = $generateNodesFromDOM(params.editor, document);
        const nodes = generatedNodes.map((node) => {
          if (!$isElementNode(node) && !$isDecoratorNode(node)) {
            const p = $createParagraphNode();
            p.append(node);
            return p;
          }

          return node;
        });
        root.append(...nodes);
        break;
      }
      case "markdown":
        return $convertFromMarkdownString(params.value, TRANSFORMERS, root);
    }
  });
}

export default function Editor(props: Props) {
  const initialConfig: InitialConfigType = {
    namespace: "MyEditor",
    editorState:
      props.initialValue !== undefined
        ? (editor) =>
            prepopulatedRichText({ value: props.initialValue!, format: props.format, editor })
        : undefined,
    onError: (error) => {
      console.error(error);
    },
    nodes: [
      HeadingNode,
      ListNode,
      ListItemNode,
      QuoteNode,
      CodeNode,
      CodeHighlightNode,
      AutoLinkNode,
      LinkNode
    ],
  };

return (
    <LexicalComposer initialConfig={initialConfig}>
         <RichTextPlugin ... />
     ...
     <LexicalComposer />
)

```

The output of `$generateNodesFromDOM` using the mentioned text gives an array of 3 items: `LineBreakNode`, `ParagraphNode`, `ParagraphNode`. We have the following map because, afaik, you can't a line break to the root by itself because it's not a decorator or an element. What's added to the root instead of my HTML is the followin:
```
<p><br><br></p>
<p dir="ltr"><span data-lexical-text="true">The following text is in a blockqoute tag:</span></p>
<p dir="ltr"><span data-lexical-text="true">blockqoute text!</span></p>
```
I don't understand where my HTML went: the tags & the styles. What am I missing?

### 2) Error: "Unable to find an active editor state" - Lexical version: 0.14.3<:
I thought that the above issue would be fixed if I updated to the latest version. After upgrading, I got an error I couldn't resolve. After trying all the versions, I found that everything below 0.14.3 works fine, and everything above it, including 0.14.3, throws the following error:
```
Unable to find an active editor state. State helpers or node methods can only be used synchronously during the callback of editor.update() or editorState.read().

Error: Unable to find an active editor state. State helpers or node methods can only be used synchronously during the callback of editor.update() or editorState.read().
    at getActiveEditorState (http://localhost:3001/@fs/Users/amittoren/GitRepos/project/node_modules/.vite/deps/lexical.js?v=cfd5e01d:6642:13)
    at $getSelection (http://localhost:3001/@fs/Users/amittoren/GitRepos/project/node_modules/.vite/deps/lexical.js?v=cfd5e01d:6299:23)
    at http://localhost:3001/@fs/Users/amittoren/GitRepos/project/src/shared/components/Lexical/plugins/ToolbarPlugin.tsx:124:23
    at http://localhost:3001/@fs/Users/amittoren/GitRepos/project/src/shared/components/Lexical/plugins/ToolbarPlugin.tsx:151:40
    at readEditorState (http://localhost:3001/@fs/Users/amittoren/GitRepos/project/node_modules/.vite/deps/chunk-ELPXPIXE.js?v=3942ab5a:6711:16)
    at EditorState.read (http://localhost:3001/@fs/Users/amittoren/GitRepos/project/node_modules/.vite/deps/chunk-ELPXPIXE.js?v=3942ab5a:7708:16)
    at http://localhost:3001/@fs/Users/amittoren/GitRepos/project/src/shared/components/Lexical/plugins/ToolbarPlugin.tsx:151:29
    at commitHookEffectListMount (http://localhost:3001/@fs/Users/amittoren/GitRepos/project/node_modules/.vite/deps/chunk-APVFSRGF.js?v=3942ab5a:16904:34)
    at invokePassiveEffectMountInDEV (http://localhost:3001/@fs/Users/amittoren/GitRepos/project/node_modules/.vite/deps/chunk-APVFSRGF.js?v=3942ab5a:18320:19)
    at invokeEffectsInDev (http://localhost:3001/@fs/Users/amittoren/GitRepos/project/node_modules/.vite/deps/chunk-APVFSRGF.js?v=3942ab5a:19697:19)
```
Here is the relevant code found in `ToolbarPlugin.tsx`:
```
function LinkPopover({ editor, disclosure }: LinkPopoverProps) {
  const [linkUrl, setLinkUrl] = React.useState("");

  const updateLinkEditor = useCallback(() => {
    const selection = $getSelection();

    if (!$isRangeSelection(selection)) {
      return;
    }

    const node = getSelectedNode(selection);
    const parent = node.getParent();

    if ($isLinkNode(parent)) {
      return setLinkUrl(parent.getURL());
    }

    if ($isLinkNode(node)) {
      return setLinkUrl(node.getURL());
    }

    return setLinkUrl("");
  }, []);

  return ( ... )
}
```

I was unable to see in the [changelog](https://github.com/facebook/lexical/releases/tag/v0.14.3) what could've caused the code to suddenly not work. [This PR](https://github.com/facebook/lexical/pull/5809/files) only added docs that seem relevant, but even if I wrapped the `prepopulatedRichText` code with `params.editor.update/read`, it threw the same error.

Would appreciate any help on these matters, or if there's anymore information I can add.

**Comment by etrepum** [comment]
If you can provide a link to a project that reproduces this error (e.g. on stackblitz or GitHub) I can look into it. If this particular error doesn't reproduce in older versions of lexical, it means you have managed to load two different versions of lexical (maybe cjs and esm, not necessarily different version numbers). It's usually a bundler configuration issue, or some dependency is bringing in a separate version of lexical which would need an override.

**Comment by etrepum** [comment]
Regarding your question about styles, nodes don't have the ability to serialize and deserialize arbitrary styles or attributes. Any information that's not handled as part of the node's importer is ignored, which includes most styles and the class attribute, among other things. In order to handle more, you would need to subclass the node(s), add the extra properties you want to handle, write the additional import/export code to handle the new properties (with a higher priority than the defaults), and include it in the editor as a replacement for the existing node type.

**Comment by amit-toren** [comment]
> If you can provide a link to a project that reproduces this error (e.g. on stackblitz or GitHub) I can look into it. If this particular error doesn't reproduce in older versions of lexical, it means you have managed to load two different versions of lexical (maybe cjs and esm, not necessarily different version numbers). It's usually a bundler configuration issue, or some dependency is bringing in a separate version of lexical which would need an override.

Thanks for the response. I didn't notice we also depend on some `@lexical/...` packages which were on version `0.11.1`. After updating them to `0.14.5` and `lexical` to the same version, everything worked again.


> Regarding your question about styles, nodes don't have the ability to serialize and deserialize arbitrary styles or attributes. Any information that's not handled as part of the node's importer is ignored, which includes most styles and the class attribute, among other things. In order to handle more, you would need to subclass the node(s), add the extra properties you want to handle, write the additional import/export code to handle the new properties (with a higher priority than the defaults), and include it in the editor as a replacement for the existing node type.

Can you maybe provide an example of how to implement that? My use case is replying to an email, so the reply chain should by stylized, to something like what Gmail does. I tried implementing a custom node that extends `ElementNode` but while the convertor and `exportDOM` are called, it doesn't seem to replace the elements with my node. Here is my code:
```
type EmailReplyChainItem = {
  citation: string;
  content: string;
};

export type SerializedEmailReplyChainNode = Spread<
  { replyChain: EmailReplyChainItem },
  SerializedElementNode
>;

function convertEmailReplyChainElement(domNode: HTMLElement): DOMConversionOutput | null {
  const citationNodes = domNode.getElementsByClassName("email-reply-chain-citation");
  const contentNodes = domNode.getElementsByClassName("email-reply-chain-content");

  if (
    citationNodes.length !== 1 ||
    contentNodes.length !== 1 ||
    citationNodes[0].textContent === null ||
    contentNodes[0].textContent === null
  ) {
    return null;
  }

  const citation = citationNodes[0].textContent;
  const content = contentNodes[0].textContent;

  const node = $createEmailReplyChainNode({ citation, content });
  return { node };
}

function createCitationElement(parent: HTMLElement, citation: string) {
  const citationElement = document.createElement("p");
  citationElement.classList.add("email-reply-chain-citation");
  citationElement.textContent = citation;
  parent.appendChild(citationElement);
}

function createContentElement(parent: HTMLElement, content: string) {
  const contentElement = document.createElement("blockquote");
  contentElement.classList.add("email-reply-chain-content");
  contentElement.textContent = content;
  parent.appendChild(contentElement);
}

export class EmailReplyChainNode extends ElementNode {
  __reply_chain: EmailReplyChainItem;

  constructor(replyChain: EmailReplyChainItem, key?: NodeKey) {
    super(key);
    this.__reply_chain = replyChain;
  }

  static getType(): string {
    return "email-reply-chain";
  }

  static clone(node: EmailReplyChainNode): EmailReplyChainNode {
    return new EmailReplyChainNode(node.__reply_chain);
  }

  static importJSON(serializedNode: SerializedEmailReplyChainNode): EmailReplyChainNode {
    const node = $createEmailReplyChainNode(serializedNode.replyChain);
    node.setFormat(serializedNode.format);
    node.setIndent(serializedNode.indent);
    node.setDirection(serializedNode.direction);
    return node;
  }

  exportJSON(): SerializedEmailReplyChainNode {
    return {
      ...super.exportJSON(),
      type: "email-reply-chain",
      replyChain: this.__reply_chain,
      version: 1,
    };
  }

  createDOM(_config: EditorConfig): HTMLElement {
    const dom = document.createElement("div");
    return dom;
  }

  exportDOM(): DOMExportOutput {
    const element = document.createElement("div");
    element.setAttribute("data-lexical-email-reply-chain", "true");
    createCitationElement(element, this.__reply_chain.citation);
    createContentElement(element, this.__reply_chain.content);
    return { element };
  }

  static importDOM(): DOMConversionMap | null {
    return {
      div: (domNode: HTMLElement) => {
        if (!domNode.hasAttribute("data-lexical-email-reply-chain")) {
          return null;
        }
        return {
          conversion: convertEmailReplyChainElement,
          priority: 4,
        };
      },
    };
  }

  updateDOM(_prevNode: EmailReplyChainNode, _dom: HTMLElement): boolean {
    return false;
  }
}

export function $createEmailReplyChainNode(
  replyChainItem: EmailReplyChainItem
): EmailReplyChainNode {
  const replyChainNode = new EmailReplyChainNode(replyChainItem);
  return $applyNodeReplacement(replyChainNode);
}

export function $isEmailReplyChainNode(
  node: LexicalNode | null | undefined
): node is EmailReplyChainNode {
  return node instanceof EmailReplyChainNode;
}
```

The HTML string I provide to `` in `` is:
```
<div data-lexical-email-reply-chain=true>
    <p class="email-reply-chain-citation">On ${date} at ${time}, ${sender} wrote:</p>
    <blockquote class="email-reply-chain-content">${message.content}</blockquote>
</div>
```

And what's rendered to the DOM is:
```
<div>
   <p dir="ltr"><span data-lexical-text="true">On 10/25/2023 at 11:16 AM, Medflyt &lt;general@mail.medflyt.com&gt; wrote:</span></p>
   <blockquote>
      <p dir="ltr"><span data-lexical-text="true">dsadsdsadsa</span></p>
   </blockquote>
</div>
```

**Comment by StyleT** [comment]
Closing this as it appears not to be an issue. Feel free to keep your discussion here or re-open it if there is indeed an issue with Lexical.

Pls also be aware that if standard node doesn't support something - you can change it within your own Lexical setup
