### ISSUE TITLE
Bug: "Cannot assign to read only property '_cachedNodes'" on undo

### ISSUE THREAD

**Issue by aleksandr-lapushkin** [facebook/lexical#6290]
Lexical version: 0.16.0

## Steps To Reproduce

1. Go to https://playground.lexical.dev/
2. Copy content from https://lexical.dev/docs/intro. Specifically, start selecting from the header and to the right, so the whole page gets selected.
3. Paste content into clean playground editor
4. Add a bit of text anywhere
5. Now, use the Undo command
6. An error is printed to the console

## The current behavior
The unminified stack trace is as follows:
```
TypeError: Cannot assign to read only property '_cachedNodes' of object '#<RangeSelection>'
    at RangeSelection.setCachedNodes (Lexical.dev.mjs:5700:1)
    at ParagraphNode.getWritable (Lexical.dev.mjs:3789:1)
    at ParagraphNode.setTextFormat (Lexical.dev.mjs:8905:1)
    at reconcileParagraphFormat (Lexical.dev.mjs:1933:1)
    at $reconcileChildrenWithDirection (Lexical.dev.mjs:1998:1)
    at $reconcileNode (Lexical.dev.mjs:2134:1)
    at $reconcileChildren (Lexical.dev.mjs:2026:1)
    at $reconcileChildrenWithDirection (Lexical.dev.mjs:1996:1)
    at $reconcileNode (Lexical.dev.mjs:2134:1)
    at $reconcileNodeChildren (Lexical.dev.mjs:2202:1)
```

I've also had cases where this happens with other selection types, not just range selections.

## The expected behavior
No errors should occur.

Video attached.

https://github.com/facebook/lexical/assets/12970405/75e3575a-8c87-43e9-a992-80f15f19f01d

**Comment by etrepum** [comment]
It looks like `reconcileParagraphFormat` is missing a `!activeEditorStateReadOnly` check like `reconcileBlockDirection` has

**Comment by aleksandr-lapushkin** [comment]
> * Go to https://playground.lexical.dev/
> * Copy content from https://lexical.dev/docs/intro. Specifically, start selecting from the header and to the right, so the whole page gets selected.
> * Paste content into clean playground editor
> * Add a bit of text anywhere
> * Now, use the Undo command
> * An error is printed to the console

Thanks! That really helped narrow it down. Opened a PR to fix the issue.
