### ISSUE TITLE
Bug: An error occurs when navigating a table with merged cells using the arrow keys(keyboard).

### ISSUE THREAD

**Issue by kmslab20** [facebook/lexical#6515]
Lexical version: 0.17.0
OS: Windows 11
Browser: Chrome latest (127.0.6533.100)

## Steps To Reproduce

1. Visit [playground](https://playground.lexical.dev/)
2. Remove all contents, and insert a table (I picked 5x5, any size is OK)
3. Merge some cells.
4. Navigate the cells using the down arrow key, from right side or inside the merged cell.

https://github.com/user-attachments/assets/6db7a0af-8853-4f6e-bcf3-74123440cea7

https://github.com/user-attachments/assets/017c8aa2-df57-4e00-adf7-abea938bf3cb

https://github.com/user-attachments/assets/43acd11c-44ae-4bb2-b60e-8db84ce13932

## The current behavior

When I navigate the table with merged cells, this error occurs in some cases:
```
Uncaught Error: Node at cords not TableCellNode.
    at rs.getCellNodeFromCordsOrThrow (main-CUjk_Nh6.js:59:32769)
    at sS (main-CUjk_Nh6.js:59:25177)
    at xc (main-CUjk_Nh6.js:59:28983)
    at Array.<anonymous> (main-CUjk_Nh6.js:59:17723)
    at Yx (main-CUjk_Nh6.js:51:24287)
    at main-CUjk_Nh6.js:51:24077
    at Jx (main-CUjk_Nh6.js:51:25451)
    at Gn (main-CUjk_Nh6.js:51:26422)
    at yg.update (main-CUjk_Nh6.js:51:43947)
    at Yx (main-CUjk_Nh6.js:51:24063)
```
I tried this in my React app, and the error message was like this:
```
Uncaught Error: Node at cords not TableCellNode.
    at TableNode.getCellNodeFromCordsOrThrow (LexicalTable.dev.mjs:2710:13)
    at selectTableNodeInDirection (LexicalTable.dev.mjs:2189:39)
    at $handleArrowKey (LexicalTable.dev.mjs:2420:16)
    at Array.<anonymous> (LexicalTable.dev.mjs:1669:95)
    at triggerCommandListeners (Lexical.dev.mjs:8113:27)
    at Lexical.dev.mjs:8097:19
    at $beginUpdate (Lexical.dev.mjs:8230:5)
    at updateEditor (Lexical.dev.mjs:8306:5)
    at LexicalEditor.update (Lexical.dev.mjs:9961:5)
    at triggerCommandListeners (Lexical.dev.mjs:8096:12)
```
After the error occurs, the lexical editor no longer works properly.

## The expected behavior
When the down arrow key is pressed, the pointer should move to the cell directly below in the same column.

## Impact of fix
Fixing this bug would improve table features, benefiting many users who use table and cell-merging features.

**Comment by Ulop** [comment]
@ivailop7 Unfortunately, this error is reproduced in another case:
- insert 4*4 table
- merge cells of the last row
- place cursor on the last row
- press down arrow key

The console will display the error:
`Uncaught Error: Node at cords not TableCellNode.`

**Comment by ivailop7** [comment]
Unable to reproduce, could you attach a screen recording.

**Comment by Ulop** [comment]
> Unable to reproduce, could you attach a screen recording.

Sorry, I previously prepared a video with playback steps, but forgot to attach it.

https://github.com/user-attachments/assets/e4b286d6-afa5-4b1d-88bc-9dc0055e6ba6
