### ISSUE TITLE
Bug: [AutocompletePlugin] - Cannot assign to read only property '_cachedNodes' of object '#<RangeSelection>' on undo

### ISSUE THREAD

**Issue by bedre7** [facebook/lexical#6843]
Lexical version: v0.20.0

## Steps To Reproduce

1. Go to lexical playground
2. Turn on autocomplete from settings
3. focus on the editor and select any format(bold for e.g)
4. type "test"
5. press tab when you see the suggestion
6. undo

## The current behavior
https://github.com/user-attachments/assets/85c551e6-055c-4687-9d7f-cd8c10a9f72a

I'm not sure if it's related to the autocomplete plugin but here is the stack trace:
```
Uncaught TypeError: Cannot assign to read only property '_cachedNodes' of object '#<RangeSelection>'
    at RangeSelection.setCachedNodes (main-C507j1EI.js:48:6194)
    at d0.getWritable (main-C507j1EI.js:45:11751)
    at d0.markDirty (main-C507j1EI.js:45:15474)
    at Array.tt (main-C507j1EI.js:55:27349)
    at $applyTransforms (main-C507j1EI.js:51:27878)
    at $applyAllTransforms (main-C507j1EI.js:51:28705)
    at $beginUpdate (main-C507j1EI.js:51:35644)
    at updateEditor (main-C507j1EI.js:51:36873)
    at LexicalEditor.update (main-C507j1EI.js:51:59695)
    at triggerCommandListeners (main-C507j1EI.js:51:33874)
```

## The expected behavior
This error should not occur

**Comment by etrepum** [comment]
This generally happens when `$setSelection(selection)` is used with a frozen selection from a previous state when the correct option is to use `$setSelection(selection.clone())`
